create table if not exists public.user_activity (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  action text not null,
  entity_type text not null,
  entity_id text,
  title text not null,
  description text,
  created_at timestamptz not null default now()
);

create index if not exists user_activity_user_created_idx
on public.user_activity (user_id, created_at desc);

alter table public.user_activity enable row level security;

drop policy if exists "Users can read their own activity" on public.user_activity;
create policy "Users can read their own activity"
on public.user_activity
for select
to authenticated
using ((select auth.uid()) = user_id);

revoke insert, update, delete on public.user_activity from anon, authenticated;
grant select on public.user_activity to authenticated;

create or replace function public.record_user_activity(
  p_user_id uuid,
  p_action text,
  p_entity_type text,
  p_entity_id text,
  p_title text,
  p_description text default null
)
returns void
language sql
security definer
set search_path = public
as $$
  insert into public.user_activity (
    user_id,
    action,
    entity_type,
    entity_id,
    title,
    description
  )
  values (
    p_user_id,
    p_action,
    p_entity_type,
    p_entity_id,
    p_title,
    p_description
  );
$$;

revoke all on function public.record_user_activity(
  uuid, text, text, text, text, text
) from public, anon, authenticated;

create or replace function public.track_space_activity()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  activity_user_id uuid;
  activity_space_id text;
  activity_space_name text;
begin
  activity_user_id := coalesce(new.user_id, old.user_id);
  activity_space_id := coalesce(new.id, old.id)::text;
  activity_space_name := coalesce(new.space_name, old.space_name, 'Parking space');

  if tg_op = 'INSERT' then
    perform public.record_user_activity(
      activity_user_id,
      'space_created',
      'space',
      activity_space_id,
      'Registered ' || activity_space_name,
      'Parking space added'
    );
    return new;
  elsif tg_op = 'UPDATE' then
    perform public.record_user_activity(
      activity_user_id,
      'space_updated',
      'space',
      activity_space_id,
      'Updated ' || activity_space_name,
      'Parking space details or availability changed'
    );
    return new;
  end if;

  perform public.record_user_activity(
    activity_user_id,
    'space_deleted',
    'space',
    activity_space_id,
    'Deleted ' || activity_space_name,
    'Parking space removed'
  );
  return old;
end;
$$;

create or replace function public.track_booking_activity()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  activity_booking public.bookings%rowtype;
  owner_id uuid;
  space_name text;
  status_title text;
begin
  activity_booking := coalesce(new, old);

  select spaces.user_id, spaces.space_name
  into owner_id, space_name
  from public.spaces
  where spaces.id = activity_booking.space_id;

  space_name := coalesce(space_name, 'a parking space');

  if tg_op = 'INSERT' then
    perform public.record_user_activity(
      activity_booking.driver_id,
      'booking_created',
      'booking',
      activity_booking.id::text,
      'Booked ' || space_name,
      'Booking confirmed'
    );

    if owner_id is not null and owner_id <> activity_booking.driver_id then
      perform public.record_user_activity(
        owner_id,
        'booking_received',
        'booking',
        activity_booking.id::text,
        space_name || ' was booked',
        'New driver booking'
      );
    end if;
    return new;
  end if;

  if tg_op = 'UPDATE' then
    if new.status is distinct from old.status then
      status_title := 'Booking at ' || space_name || ' changed to ' || new.status;

      perform public.record_user_activity(
        new.driver_id,
        'booking_status_changed',
        'booking',
        new.id::text,
        status_title,
        'Booking status updated'
      );

      if owner_id is not null and owner_id <> new.driver_id then
        perform public.record_user_activity(
          owner_id,
          'booking_status_changed',
          'booking',
          new.id::text,
          status_title,
          'Booking status updated'
        );
      end if;
    end if;

    if new.driver_hidden_at is not null and old.driver_hidden_at is null then
      perform public.record_user_activity(
        new.driver_id,
        'booking_removed',
        'booking',
        new.id::text,
        'Removed booking at ' || space_name,
        'Hidden from My Bookings'
      );
    end if;
    return new;
  end if;

  perform public.record_user_activity(
    old.driver_id,
    'booking_deleted',
    'booking',
    old.id::text,
    'Booking at ' || space_name || ' was deleted',
    'Booking record removed'
  );
  return old;
end;
$$;

revoke all on function public.track_space_activity() from public, anon, authenticated;
revoke all on function public.track_booking_activity() from public, anon, authenticated;

drop trigger if exists track_space_activity_trigger on public.spaces;
create trigger track_space_activity_trigger
after insert or update or delete on public.spaces
for each row execute function public.track_space_activity();

drop trigger if exists track_booking_activity_trigger on public.bookings;
create trigger track_booking_activity_trigger
after insert or update or delete on public.bookings
for each row execute function public.track_booking_activity();
